### ISSUE TITLE
does not allow export with the print to pdf plugin

### ISSUE THREAD

**Issue by guillermohaad** [ticgal/costs#1]
Once the case is closed and I'm going to export with the print to pdf plugin, it shows me a blank page.
![printopdf](https://user-images.githubusercontent.com/12921805/46873520-684b0600-cdfc-11e8-96bf-e74c62f1181b.png)

**Comment by OscarBeiro** [comment]
Hi @guillermohaad :)
We need to check if there is need for some additional development to integrate with PDF plugin.
https://forge.glpi-project.org/projects/pdf/wiki/En_devdoc

**Comment by OscarBeiro** [comment]
Hi @guillermohaad 
We've review the issue and this is not a Costs bug, but a missing dependency for the  PDF plugin.
You need to install the intl php module.
You could report it to PDF plugin mantainers, for them to add an additional check for this dependency.
I've tried but the old GLPI forge won't allow me
https://forge.glpi-project.org/projects/pdf/issues

**Comment by guillermohaad** [comment]
thank you @OscarBeiro Osca
I'm going to request this to see how it's going

**Comment by yllen** [comment]
Done for PDF plugin for glpi >= 9.2 (https://forge.glpi-project.org/news/386)

**Comment by Rufilds** [comment]
Anyone has the plugin for 9.3??

**Comment by Rufilds** [comment]
> Hi @guillermohaad
> We've review the issue and this is not a Costs bug, but a missing dependency for the PDF plugin.
> You need to install the intl php module.
> You could report it to PDF plugin mantainers, for them to add an additional check for this dependency.
> I've tried but the old GLPI forge won't allow me
> https://forge.glpi-project.org/projects/pdf/issues

How i install the ntl php module? can you help?

**Comment by OscarBeiro** [comment]
This is not the PDF plugin support place, but COSTS plugin @Rufilds .
Anyway, there's already a 9.3 compatible PDF plugin.
Intl PHP module is installed in different ways, depending on your OS and PHP version.
You can use:
`apt install php7.0-intl`
For a Debian derivative OS and PHP 7.0
