### ISSUE TITLE
Apply or not a cost per task when closing tickets

### ISSUE THREAD

**Issue by cedricdemeulder** [ticgal/costs#10]
Hello,
It could be a nice feature to exclude a task from billing when a ticket is closed.
Regards

**Comment by OscarBeiro** [comment]
Hi again, :)
This was pretty much answered on #9.

By setting your tasks to private, they won't be taken into consideration on close.

In the upcoming release, this will be done per task and not at ticket closing, but otherwise, the behaviour will stay the same.

Cheers,
