### ISSUE TITLE
Costs by profiles/tiltles

### ISSUE THREAD

**Issue by GuiBalestro** [ticgal/costs#2]
Hi,

It's a greatfull plugin, congratulations!

To make it better, my suggestion is to allow to create costs by profiles or by titles, in that way will be possible to have different time costs.
Technician 1 - $5,00 
Technician 2 - $7,00
Technician 3 - $10,00

**Comment by OscarBeiro** [comment]
Hi @GuiBalestro,

That's a great idea but would need extra development.
If you are interested in funding it please drop us a line at hello[at]ticgal[dot]com

Regards

**Comment by OscarBeiro** [comment]
Ready for next release.
