### ISSUE TITLE
PHP Notice (8): Undefined index: entities_id in /opt/glpi/marketplace/costs/inc/ticket.class.php at line 123

### ISSUE THREAD

**Issue by NazarovRoman** [ticgal/costs#23]
The attached image shows under what circumstances the problem occurs.

Error 1: PHP Notice (8): Undefined index: entities_id in /opt/glpi/marketplace/costs/inc/ticket.class.php at line 123

Error 2: SQL Error "1048": Column 'entities_id' cannot be null in query "INSERT INTO `glpi_plugin_costs_entities` (`entities_id`) VALUES (NULL)"

Error 3: PHP Notice (8): Undefined index: inheritance in /opt/glpi/marketplace/costs/inc/ticket.class.php at line 124

Error 4: PHP Notice (8): Undefined index: auto_cost in /opt/glpi/marketplace/costs/inc/ticket.class.php at line 128

![2022-10-20_224310](https://user-images.githubusercontent.com/40058572/197008936-90759e9a-15db-44be-bc9e-8685e43330c6.png)

**Comment by gitsyncuser** [comment]
<p>Hello,</p>\r\n<p><br>Please submit the error in php-error.log and the version of glpi and the plugin</p>\r\n<p><br>thanks</p><blockquote>Creado por <a href='https://tic.gal'>GitSync</a> en GLPI por Bernardo Ballesteros</blockquote>

**Comment by NazarovRoman** [comment]
LOGS: 
[access-errors.log](https://github.com/ticgal/costs/files/9930922/access-errors.log)
[php-errors.log](https://github.com/ticgal/costs/files/9930923/php-errors.log)
[sql-errors.log](https://github.com/ticgal/costs/files/9930925/sql-errors.log)
