### ISSUE TITLE
Costs doesn't work any longer since update

### ISSUE THREAD

**Issue by PresentsSI** [ticgal/costs#26]
Hi,
the Costs plugin doesn't work since we upgrarded to 3.0.3
When validating a new task, we have got a blank page.
The task is created but no cost line is added
And the configuration page for the plugin is empty

**Comment by FrancisTicgal** [comment]
Hello, can you please provide us with the version of your GLPI and the related errors in the php-errors.log file?

The latest versions only fix the positioning of the dropdown and a warning that the identifier fields do not support negative numbers, with no changes to the functionality of the costs.

**Comment by PresentsSI** [comment]
Hello,
We are using GLPI 10.0.7 ; I will upgrade it to 10.0.12 to check if the problem remains

Here is the log file content :

- when I try to access the config page http://myGLPI/marketplace/costs/front/config.form.php

[2024-03-08 16:35:54] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Return value of PluginCostsConfig::getInstance() must be an instance of mixed, instance of PluginCostsConfig returned in /var/www/html/marketplace/costs/inc/config.class.php at line 82
  Backtrace :
  marketplace/costs/inc/config.class.php:111         PluginCostsConfig::getInstance()
  marketplace/costs/inc/config.class.php:151         PluginCostsConfig::showConfigForm()
  src/CommonGLPI.php:689                             PluginCostsConfig::displayTabContentForItem()
  ajax/common.tabs.php:116                           CommonGLPI::displayStandardTab()
  public/index.php:73                                require()

- when I try to add a task to a ticket :

[2024-03-08 16:36:56] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Return value of PluginCostsTicket::isBillable() must be an instance of mixed, int returned in /var/www/html/marketplace/costs/inc/ticket.class.php at line 110
  Backtrace :
  marketplace/costs/inc/task.class.php:60            PluginCostsTicket::isBillable()
  src/Plugin.php:1617                                PluginCostsTask::taskAdd()
  src/CommonDBTM.php:1364                            Plugin::doHook()
  front/commonitiltask.form.php:67                   CommonDBTM->add()
  front/tickettask.form.php:39                       include()
  public/index.php:73                                require()

**Comment by PresentsSI** [comment]
I upgraded my debian server to Bookworm and thus PHP to version 8
Everything seems to work fine now

**Comment by OscarBeiro** [comment]
So this was a PHP 7.4 issue.
Thanks for the feedback.
