### ISSUE TITLE
Show the credit available

### ISSUE THREAD

**Issue by Jeff-Tall** [ticgal/costs#3]
Hello,

Is it possible to display the credit available after selection of the contract and when writing a task, follow-up or solution ?

Thanks

**Comment by OscarBeiro** [comment]
Hi @Jeff-Tall,

I don't understand what you mean.  Costs doesn't currently manage a concept as credit available.
Could you possibly be talking about Credit plugin? https://github.com/pluginsGLPI/credit

Regards

**Comment by Jeff-Tall** [comment]
Oups.

Yes, sorry.

**Comment by OscarBeiro** [comment]
No worries :)
