### ISSUE TITLE
plugin dont works

### ISSUE THREAD

**Issue by juliosw** [ticgal/costs#6]
I did the installation and configuration of the plugin according to the documentation.

I added tasks and solved the ticket, but the costs do not appear.

GLPI Version 9.4.2

![image](https://user-images.githubusercontent.com/45014255/72914934-3c684100-3d1e-11ea-955a-b170d0cc91e7.png)

**Comment by OscarBeiro** [comment]
Sorry about the late answer.
Costs are applied when the ticket state is solved. Add a solution and tell us if costs are generated.

Regards,
