### ISSUE TITLE
Private task in entities configuration

### ISSUE THREAD

**Issue by cedricdemeulder** [ticgal/costs#9]
Hello,
Could you please explain waht is the "Pricate Task" used for in the entity configuration?
Regards

**Comment by OscarBeiro** [comment]
Hi Cedric,

Sorry about the delay.

We are waiting for the upcoming Costs release to publish a post with more information, like a manual. This plugin started as a quite simple one, covering an important GLPI need, but has evolved to something more complex, as you'll see soon.

Meanwhile, here you have the requested explanation. If you check Private tasks, time involved in private tasks will generate costs, while if disabled, it won't.


Cheers,
